import { createFileRoute } from "@tanstack/react-router";
const S = "https://pawandfound.store";
const B = "https://buy.stripe.com/8x28wPg2i9SE6MN7ao2cg0K";
const P = "https://buy.stripe.com/fZu28rbM27Kw9YZfGU2cg12";
const T = [{ n: "Karen W.", t: "When my dog started choking on a treat, I froze. After reading this handbook, I knew exactly what to do. The step-by-step instructions with clear diagrams saved me from panic. Every pet owner needs this.", r: 5 }, { n: "Mike R.", t: "I keep this PDF on my phone. Used it twice already — once for a cut paw on a hike and once when my cat ate something questionable. The poisoning section is worth the price alone.", r: 5 }, { n: "Lisa T.", t: "The pet CPR section is so clearly written. I practiced on a stuffed animal and now feel genuinely prepared. This gave me the confidence to handle emergencies without freezing up.", r: 5 }];

export const Route = createFileRoute("/ebooks/pet-first-aid-handbook")({
  component: Page,
  head: () => ({ meta: [{ title: "Pet First Aid & Emergency Handbook — Paw & Found" }, { name: "description", content: "Be prepared for pet emergencies. Covers wound care, choking, poisoning, heatstroke, seizures, CPR, and when to rush to the vet." }], links: [{ rel: "canonical", href: `${S}/ebooks/pet-first-aid-handbook` }] }),
});

function Page() {
  const chapters = [
    { c: "1", t: "Building a Pet First Aid Kit", d: "Exactly what you need and where to keep it — a complete checklist with budget-friendly options" },
    { c: "2", t: "Wound Care & Bandaging", d: "How to clean, dress, and bandage cuts, scrapes, and punctures — with illustrated techniques" },
    { c: "3", t: "Choking & Airway Emergencies", d: "Step-by-step response for conscious and unconscious pets — including breed-specific modifications" },
    { c: "4", t: "Poisoning & Toxic Substances", d: "Master list of toxic foods, plants, and household products — what to do immediately and what NOT to do" },
    { c: "5", t: "Heatstroke & Cold Emergencies", d: "Recognizing early signs, cooling and warming techniques, and prevention strategies for extreme weather" },
    { c: "6", t: "Seizures & Neurological Events", d: "What to do during a seizure, how to document for your vet, and when it's a true emergency" },
    { c: "7", t: "Pet CPR Basics", d: "Clear, illustrated CPR instructions for dogs and cats — chest compressions, rescue breathing, and rhythm" },
    { c: "8", t: "When to Rush to the Vet", d: "The definitive red-flag checklist — symptoms that mean drop everything and go, versus what can wait until morning" },
  ];
  return (<div>
    <div className="bg-gradient-to-b from-[#FFF8F0] to-white"><div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8"><div className="flex flex-col items-center gap-8 md:flex-row md:items-start"><div className="flex-shrink-0"><img src="/images/ebook-pet-first-aid-handbook.jpg" alt="Pet First Aid & Emergency Handbook cover" className="w-56 rounded-xl shadow-2xl shadow-[#2A9D8F]/20 md:w-64" /></div><div className="flex-1 text-center md:text-left"><span className="inline-flex items-center rounded-full bg-[#2A9D8F]/15 px-3 py-1 text-sm font-semibold text-[#2A9D8F]">Premium eBook</span><h1 className="font-heading mt-3 text-3xl font-bold text-[#2D2D2D] sm:text-4xl">Pet First Aid & Emergency Handbook</h1><p className="mt-4 text-lg text-[#6B7280] leading-relaxed max-w-xl">Emergencies don't wait. Be the calm, prepared pet parent who knows exactly what to do when every second counts.</p><div className="mt-6 flex flex-wrap items-center gap-4 justify-center md:justify-start"><span className="font-heading text-3xl font-bold text-[#FF7F5C]">$14.99</span><a href={P} className="btn-primary text-base px-8 py-3">Buy Now — Instant Download</a></div><p className="mt-2 text-xs text-[#6B7280]">Secure payment via Stripe. 30-day money-back guarantee.</p></div></div></div></div>
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8"><h2 className="font-heading text-center text-2xl font-bold text-[#2D2D2D]">What's Inside</h2><p className="mt-2 text-center text-[#6B7280]">8 chapters covering every common pet emergency with clear, actionable instructions</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{chapters.map((ch) => (<div key={ch.c} className="flex gap-3 rounded-lg border border-[#E9EDDE] bg-white p-4"><span className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-[#2A9D8F]/15 text-sm font-bold text-[#2A9D8F]">{ch.c}</span><div><h3 className="font-heading text-sm font-semibold text-[#2D2D2D]">{ch.t}</h3><p className="mt-0.5 text-xs text-[#6B7280]">{ch.d}</p></div></div>))}</div></div>
    <div className="bg-[#FFF8F0] py-12"><div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-heading text-2xl font-bold text-[#2D2D2D]">Why This Handbook?</h2><div className="mt-8 grid gap-6 sm:grid-cols-3">{[{ i: "🏥", t: "Veterinarian-Reviewed", d: "Every procedure checked by emergency veterinarians for accuracy, safety, and clarity" }, { i: "📋", t: "Quick-Reference Design", d: "Step-by-step checklists designed for high-stress situations — find what you need in seconds" }, { i: "📱", t: "Always With You", d: "PDF on your phone — pull it up at the dog park, on a hike, or anywhere emergencies happen" }].map((b) => (<div key={b.t}><span className="text-3xl">{b.i}</span><h3 className="font-heading mt-2 font-semibold text-[#2D2D2D]">{b.t}</h3><p className="mt-1 text-sm text-[#6B7280]">{b.d}</p></div>))}</div></div></div>
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8"><h2 className="font-heading text-center text-2xl font-bold text-[#2D2D2D]">What Pet Parents Say</h2><div className="mt-6 space-y-4">{T.map((t) => (<div key={t.n} className="rounded-xl border border-[#E9EDDE] bg-white p-5"><div className="flex items-center gap-2"><span className="font-heading text-sm font-semibold text-[#2D2D2D]">{t.n}</span><span className="text-[#F4A261] text-sm">{"★".repeat(t.r)}</span></div><p className="mt-2 text-sm text-[#4A4A4A] leading-relaxed">{t.t}</p></div>))}</div></div>
    <div className="border-t border-[#E9EDDE] bg-gradient-to-b from-[#FFF8F0] to-white py-12"><div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-heading text-2xl font-bold text-[#2D2D2D]">Be Prepared for Anything</h2><div className="mt-6"><span className="font-heading text-4xl font-bold text-[#FF7F5C]">$14.99</span><p className="mt-1 text-sm text-[#6B7280]">Instant PDF download · 30-day money-back guarantee</p><a href={P} className="btn-primary mt-4 inline-block text-base px-10 py-4">Buy Now — Instant Download</a></div><div className="mt-10 rounded-2xl border-2 border-[#F4A261] bg-white p-6 shadow-md"><span className="inline-flex items-center rounded-full bg-[#F4A261] px-3 py-1 text-xs font-bold text-white">BEST VALUE</span><h3 className="font-heading mt-3 text-lg font-semibold text-[#2D2D2D]">Get the Complete Pet Library</h3><p className="mt-1 text-sm text-[#6B7280]">Includes this handbook plus all our premium eBooks — first aid, training, nutrition, breed guides, and more.</p><div className="mt-3 flex items-center justify-center gap-2"><span className="text-lg text-[#6B7280] line-through">Over $120</span><span className="font-heading text-2xl font-bold text-[#FF7F5C]">$49.99</span></div><a href={B} className="btn-secondary mt-3 inline-block">Get the Bundle Instead</a></div></div></div>
  </div>);
}
