import { createFileRoute } from "@tanstack/react-router";
const S = "https://pawandfound.store", B = "https://buy.stripe.com/8x28wPg2i9SE6MN7ao2cg0K", P = "https://buy.stripe.com/fZu9AT03k0i42wxcuI2cg11";
const T = [{ n: "Jenny F.", t: "I never thought about paw care in winter until our dog got ice burns. This guide covers everything season by season — now I feel prepared for every weather change.", r: 5 }, { n: "Thomas G.", t: "The holiday hazards section is a lifesaver. I had no idea how many Christmas decorations and foods were dangerous for pets. This should be required reading for every pet owner.", r: 5 }, { n: "Rebecca L.", t: "We moved from Florida to Minnesota and had no idea how to handle winter with our dog. This guide walked us through cold protection, paw balms, and even dog coat recommendations. So practical.", r: 5 }];

export const Route = createFileRoute("/ebooks/seasonal-pet-care")({
  component: Page,
  head: () => ({ meta: [{ title: "The Seasonal Pet Care Guide — Paw & Found" }, { name: "description", content: "Year-round pet care: spring allergies, summer heat safety, fall anxiety, winter protection, holiday hazards, and seasonal grooming tips." }], links: [{ rel: "canonical", href: `${S}/ebooks/seasonal-pet-care` }] }),
});

function Page() {
  const ch = [
    { c: "1", t: "Spring: Allergies & Shedding", d: "Managing seasonal allergies, excessive shedding, and spring cleaning hazards for pets" },
    { c: "2", t: "Summer: Heat Safety & Hydration", d: "Preventing heatstroke, paw protection on hot pavement, water safety, and hydration strategies" },
    { c: "3", t: "Fall: Back-to-School Anxiety", d: "How routine changes affect pets — separation anxiety prevention and enrichment for lonelier days" },
    { c: "4", t: "Winter: Cold Protection & Antifreeze Dangers", d: "Frostbite prevention, safe de-icers, winter gear guide, and the hidden dangers of antifreeze" },
    { c: "5", t: "Holiday Hazards by Season", d: "Easter lilies, Halloween candy, Thanksgiving bones, Christmas trees — a complete seasonal danger checklist" },
    { c: "6", t: "Paw Care Year-Round", d: "Seasonal paw maintenance — balms, booties, trimming, and treating cracked pads in any weather" },
    { c: "7", t: "Seasonal Grooming Guide", d: "Coat care through the seasons — when to trim, when to let it grow, and breed-specific seasonal tips" },
  ];
  return (<div>
    <div className="bg-gradient-to-b from-[#FFF8F0] to-white"><div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8"><div className="flex flex-col items-center gap-8 md:flex-row md:items-start"><div className="flex-shrink-0"><img src="/images/ebook-seasonal-pet-care.jpg" alt="Seasonal Pet Care Guide cover" className="w-56 rounded-xl shadow-2xl shadow-[#F4A261]/20 md:w-64" /></div><div className="flex-1 text-center md:text-left"><span className="inline-flex items-center rounded-full bg-[#F4A261]/15 px-3 py-1 text-sm font-semibold text-[#D4891E]">Premium eBook</span><h1 className="font-heading mt-3 text-3xl font-bold text-[#2D2D2D] sm:text-4xl">The Seasonal Pet Care Guide</h1><p className="mt-4 text-lg text-[#6B7280] leading-relaxed max-w-xl">Every season brings new joys and new risks for your pet. Stay one step ahead with practical, season-by-season guidance.</p><div className="mt-6 flex flex-wrap items-center gap-4 justify-center md:justify-start"><span className="font-heading text-3xl font-bold text-[#FF7F5C]">$12.99</span><a href={P} className="btn-primary text-base px-8 py-3">Buy Now — Instant Download</a></div><p className="mt-2 text-xs text-[#6B7280]">Secure payment via Stripe. 30-day money-back guarantee.</p></div></div></div></div>
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8"><h2 className="font-heading text-center text-2xl font-bold text-[#2D2D2D]">What's Inside</h2><p className="mt-2 text-center text-[#6B7280]">7 chapters covering every season's unique challenges and opportunities</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{ch.map((c) => (<div key={c.c} className="flex gap-3 rounded-lg border border-[#E9EDDE] bg-white p-4"><span className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-[#F4A261]/15 text-sm font-bold text-[#D4891E]">{c.c}</span><div><h3 className="font-heading text-sm font-semibold text-[#2D2D2D]">{c.t}</h3><p className="mt-0.5 text-xs text-[#6B7280]">{c.d}</p></div></div>))}</div></div>
    <div className="bg-[#FFF8F0] py-12"><div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-heading text-2xl font-bold text-[#2D2D2D]">Why This Guide?</h2><div className="mt-8 grid gap-6 sm:grid-cols-3">{[{ i: "🌤️", t: "Season-by-Season Clarity", d: "Never wonder what changes with the weather — each chapter covers exactly what to do and when" }, { i: "🩺", t: "Veterinarian-Reviewed", d: "All seasonal health risks and recommendations reviewed by licensed vets" }, { i: "📱", t: "Always With You", d: "PDF on all devices — check holiday hazard lists while decorating or summer safety tips before a heat wave" }].map((b) => (<div key={b.t}><span className="text-3xl">{b.i}</span><h3 className="font-heading mt-2 font-semibold text-[#2D2D2D]">{b.t}</h3><p className="mt-1 text-sm text-[#6B7280]">{b.d}</p></div>))}</div></div></div>
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8"><h2 className="font-heading text-center text-2xl font-bold text-[#2D2D2D]">What Pet Parents Say</h2><div className="mt-6 space-y-4">{T.map((t) => (<div key={t.n} className="rounded-xl border border-[#E9EDDE] bg-white p-5"><div className="flex items-center gap-2"><span className="font-heading text-sm font-semibold text-[#2D2D2D]">{t.n}</span><span className="text-[#F4A261] text-sm">{"★".repeat(t.r)}</span></div><p className="mt-2 text-sm text-[#4A4A4A] leading-relaxed">{t.t}</p></div>))}</div></div>
    <div className="border-t border-[#E9EDDE] bg-gradient-to-b from-[#FFF8F0] to-white py-12"><div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-heading text-2xl font-bold text-[#2D2D2D]">Keep Your Pet Safe All Year Long</h2><div className="mt-6"><span className="font-heading text-4xl font-bold text-[#FF7F5C]">$12.99</span><p className="mt-1 text-sm text-[#6B7280]">Instant PDF download · 30-day money-back guarantee</p><a href={P} className="btn-primary mt-4 inline-block text-base px-10 py-4">Buy Now — Instant Download</a></div><div className="mt-10 rounded-2xl border-2 border-[#F4A261] bg-white p-6 shadow-md"><span className="inline-flex items-center rounded-full bg-[#F4A261] px-3 py-1 text-xs font-bold text-white">BEST VALUE</span><h3 className="font-heading mt-3 text-lg font-semibold text-[#2D2D2D]">Get the Complete Pet Library</h3><p className="mt-1 text-sm text-[#6B7280]">Includes this guide plus all our premium eBooks — seasonal care, health, training, and more.</p><div className="mt-3 flex items-center justify-center gap-2"><span className="text-lg text-[#6B7280] line-through">Over $120</span><span className="font-heading text-2xl font-bold text-[#FF7F5C]">$49.99</span></div><a href={B} className="btn-secondary mt-3 inline-block">Get the Bundle Instead</a></div></div></div>
  </div>);
}
