import { createFileRoute } from "@tanstack/react-router";
const S = "https://pawandfound.store", B = "https://buy.stripe.com/8x28wPg2i9SE6MN7ao2cg0K", P = "https://buy.stripe.com/8x25kD7vM9SE8UV1Q42cg14";
const T = [{ n: "Jake M.", t: "We took our golden retriever on a 2-week road trip using this guide. The packing checklist was perfect — didn't forget a thing. And the pet-friendly hotel directory saved us hours of searching.", r: 5 }, { n: "Emma R.", t: "Flying with my cat was terrifying until I read the airline section. Knew exactly which carrier to buy, what documents I needed, and how to keep her calm. The flight went so smoothly.", r: 5 }, { n: "Sarah H.", t: "The camping and hiking chapter gave us the confidence to take our dog on real adventures. The gear checklist and safety tips made our first camping trip with him a huge success.", r: 5 }];

export const Route = createFileRoute("/ebooks/pet-travel-adventure")({
  component: Page,
  head: () => ({ meta: [{ title: "The Pet Travel & Adventure Guide — Paw & Found" }, { name: "description", content: "Everything you need to travel with your pet: road trips, flying, camping, hiking, anxiety management, international requirements, and gear checklists." }], links: [{ rel: "canonical", href: `${S}/ebooks/pet-travel-adventure` }] }),
});

function Page() {
  const ch = [
    { c: "1", t: "Road Trip Planning & Safety", d: "Car restraints, rest stop strategy, car sickness prevention, and never-leave-behind packing lists" },
    { c: "2", t: "Flying with Your Pet", d: "Airline policies decoded, approved carrier dimensions, sedation do's and don'ts, and airport navigation tips" },
    { c: "3", t: "Camping & Hiking Essentials", d: "Trail safety, wildlife awareness, paw protection on rough terrain, and Leave No Trace for pets" },
    { c: "4", t: "Pet-Friendly Lodging Guide", d: "Finding truly pet-friendly hotels, avoiding surprise fees, Airbnb tips, and what to ask before booking" },
    { c: "5", t: "Anxiety & Motion Sickness", d: "Natural remedies, desensitization training, and when medication is appropriate — for cars, planes, and new places" },
    { c: "6", t: "International Travel Requirements", d: "Pet passports, microchip requirements, quarantine rules, and country-specific regulations explained" },
    { c: "7", t: "Adventure Gear Checklist", d: "The ultimate packing list — from collapsible bowls to first aid kits to GPS trackers — for every type of trip" },
  ];
  return (<div>
    <div className="bg-gradient-to-b from-[#FFF8F0] to-white"><div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8"><div className="flex flex-col items-center gap-8 md:flex-row md:items-start"><div className="flex-shrink-0"><img src="/images/ebook-pet-travel-adventure.jpg" alt="Pet Travel & Adventure Guide cover" className="w-56 rounded-xl shadow-2xl shadow-[#2A9D8F]/20 md:w-64" /></div><div className="flex-1 text-center md:text-left"><span className="inline-flex items-center rounded-full bg-[#2A9D8F]/15 px-3 py-1 text-sm font-semibold text-[#2A9D8F]">Premium eBook</span><h1 className="font-heading mt-3 text-3xl font-bold text-[#2D2D2D] sm:text-4xl">The Pet Travel & Adventure Guide</h1><p className="mt-4 text-lg text-[#6B7280] leading-relaxed max-w-xl">Don't leave your best friend behind. Master the art of traveling with your pet — from weekend road trips to international adventures.</p><div className="mt-6 flex flex-wrap items-center gap-4 justify-center md:justify-start"><span className="font-heading text-3xl font-bold text-[#FF7F5C]">$14.99</span><a href={P} className="btn-primary text-base px-8 py-3">Buy Now — Instant Download</a></div><p className="mt-2 text-xs text-[#6B7280]">Secure payment via Stripe. 30-day money-back guarantee.</p></div></div></div></div>
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8"><h2 className="font-heading text-center text-2xl font-bold text-[#2D2D2D]">What's Inside</h2><p className="mt-2 text-center text-[#6B7280]">7 chapters covering every mode of pet travel and adventure</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{ch.map((c) => (<div key={c.c} className="flex gap-3 rounded-lg border border-[#E9EDDE] bg-white p-4"><span className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-[#2A9D8F]/15 text-sm font-bold text-[#2A9D8F]">{c.c}</span><div><h3 className="font-heading text-sm font-semibold text-[#2D2D2D]">{c.t}</h3><p className="mt-0.5 text-xs text-[#6B7280]">{c.d}</p></div></div>))}</div></div>
    <div className="bg-[#FFF8F0] py-12"><div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-heading text-2xl font-bold text-[#2D2D2D]">Why This Guide?</h2><div className="mt-8 grid gap-6 sm:grid-cols-3">{[{ i: "✈️", t: "Comprehensive Coverage", d: "Road, air, trail, and international — every travel mode covered with specific, actionable advice" }, { i: "🩺", t: "Veterinarian-Reviewed", d: "Health and safety recommendations checked by travel-savvy veterinarians" }, { i: "📱", t: "Always With You", d: "PDF on all devices — access checklists at the airport, trailhead, or hotel check-in" }].map((b) => (<div key={b.t}><span className="text-3xl">{b.i}</span><h3 className="font-heading mt-2 font-semibold text-[#2D2D2D]">{b.t}</h3><p className="mt-1 text-sm text-[#6B7280]">{b.d}</p></div>))}</div></div></div>
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8"><h2 className="font-heading text-center text-2xl font-bold text-[#2D2D2D]">What Adventurers Say</h2><div className="mt-6 space-y-4">{T.map((t) => (<div key={t.n} className="rounded-xl border border-[#E9EDDE] bg-white p-5"><div className="flex items-center gap-2"><span className="font-heading text-sm font-semibold text-[#2D2D2D]">{t.n}</span><span className="text-[#F4A261] text-sm">{"★".repeat(t.r)}</span></div><p className="mt-2 text-sm text-[#4A4A4A] leading-relaxed">{t.t}</p></div>))}</div></div>
    <div className="border-t border-[#E9EDDE] bg-gradient-to-b from-[#FFF8F0] to-white py-12"><div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-heading text-2xl font-bold text-[#2D2D2D]">Adventure Awaits — Bring Your Pet Along</h2><div className="mt-6"><span className="font-heading text-4xl font-bold text-[#FF7F5C]">$14.99</span><p className="mt-1 text-sm text-[#6B7280]">Instant PDF download · 30-day money-back guarantee</p><a href={P} className="btn-primary mt-4 inline-block text-base px-10 py-4">Buy Now — Instant Download</a></div><div className="mt-10 rounded-2xl border-2 border-[#F4A261] bg-white p-6 shadow-md"><span className="inline-flex items-center rounded-full bg-[#F4A261] px-3 py-1 text-xs font-bold text-white">BEST VALUE</span><h3 className="font-heading mt-3 text-lg font-semibold text-[#2D2D2D]">Get the Complete Pet Library</h3><p className="mt-1 text-sm text-[#6B7280]">Includes this guide plus all our premium eBooks — travel, health, training, enrichment, and more.</p><div className="mt-3 flex items-center justify-center gap-2"><span className="text-lg text-[#6B7280] line-through">Over $120</span><span className="font-heading text-2xl font-bold text-[#FF7F5C]">$49.99</span></div><a href={B} className="btn-secondary mt-3 inline-block">Get the Bundle Instead</a></div></div></div>
  </div>);
}
