import { createFileRoute } from "@tanstack/react-router";
const S = "https://pawandfound.store", B = "https://buy.stripe.com/8x28wPg2i9SE6MN7ao2cg0K", P = "https://buy.stripe.com/3cIaEX17o2qc1st3Yc2cg13";
const T = [{ n: "Holly K.", t: "My dog gets bored so easily and I was spending a fortune on puzzle toys. The DIY food puzzles in this guide use stuff I already have at home. He's entertained for hours and I saved so much money.", r: 5 }, { n: "Chris D.", t: "The scent work games transformed our rainy day routine. My high-energy border collie now gets mental stimulation even when we can't go outside. The difference in his behavior is incredible.", r: 5 }, { n: "Maria V.", t: "My senior cat was getting lethargic until I tried the enrichment ideas in this book. Simple things like cardboard box mazes and treat trails brought her personality back. I wish I'd found this sooner.", r: 5 }];

export const Route = createFileRoute("/ebooks/diy-pet-enrichment")({
  component: Page,
  head: () => ({ meta: [{ title: "The DIY Pet Enrichment Guide — Paw & Found" }, { name: "description", content: "Keep your pet happy and mentally stimulated with homemade toys, puzzles, scent games, and enrichment activities — all using household items." }], links: [{ rel: "canonical", href: `${S}/ebooks/diy-pet-enrichment` }] }),
});

function Page() {
  const ch = [
    { c: "1", t: "Scent Work & Nose Games", d: "Tap into your dog's most powerful sense with simple scent detection games using treats, essential oils, and household items" },
    { c: "2", t: "DIY Food Puzzles", d: "Step-by-step instructions for homemade puzzle feeders — muffin tin games, towel rolls, bottle spinners, and more" },
    { c: "3", t: "Homemade Toys from Household Items", d: "Turn cardboard boxes, old t-shirts, plastic bottles, and socks into engaging toys your pet will love" },
    { c: "4", t: "Backyard Agility on a Budget", d: "Build a complete agility course using PVC pipes, pool noodles, broomsticks, and other affordable materials" },
    { c: "5", t: "Mental Stimulation for Senior Pets", d: "Gentle enrichment activities adapted for older dogs and cats — keeping minds sharp without physical strain" },
    { c: "6", t: "Indoor Games for Rainy Days", d: "Hide-and-seek, stairway fetch, hallway soccer, and other games that burn energy without needing outdoor space" },
    { c: "7", t: "Enrichment for Cats", d: "Cat-specific activities: window watching stations, wand toy DIY, paper bag adventures, and vertical exploration" },
  ];
  return (<div>
    <div className="bg-gradient-to-b from-[#FFF8F0] to-white"><div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8"><div className="flex flex-col items-center gap-8 md:flex-row md:items-start"><div className="flex-shrink-0"><img src="/images/ebook-diy-pet-enrichment.jpg" alt="DIY Pet Enrichment Guide cover" className="w-56 rounded-xl shadow-2xl shadow-[#F4A261]/20 md:w-64" /></div><div className="flex-1 text-center md:text-left"><span className="inline-flex items-center rounded-full bg-[#F4A261]/15 px-3 py-1 text-sm font-semibold text-[#D4891E]">Premium eBook</span><h1 className="font-heading mt-3 text-3xl font-bold text-[#2D2D2D] sm:text-4xl">The DIY Pet Enrichment Guide</h1><p className="mt-4 text-lg text-[#6B7280] leading-relaxed max-w-xl">A happy pet is a stimulated pet. Discover dozens of creative, budget-friendly enrichment activities using items you already have at home.</p><div className="mt-6 flex flex-wrap items-center gap-4 justify-center md:justify-start"><span className="font-heading text-3xl font-bold text-[#FF7F5C]">$12.99</span><a href={P} className="btn-primary text-base px-8 py-3">Buy Now — Instant Download</a></div><p className="mt-2 text-xs text-[#6B7280]">Secure payment via Stripe. 30-day money-back guarantee.</p></div></div></div></div>
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8"><h2 className="font-heading text-center text-2xl font-bold text-[#2D2D2D]">What's Inside</h2><p className="mt-2 text-center text-[#6B7280]">7 chapters packed with creative, cheap, and fun enrichment ideas</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{ch.map((c) => (<div key={c.c} className="flex gap-3 rounded-lg border border-[#E9EDDE] bg-white p-4"><span className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-[#F4A261]/15 text-sm font-bold text-[#D4891E]">{c.c}</span><div><h3 className="font-heading text-sm font-semibold text-[#2D2D2D]">{c.t}</h3><p className="mt-0.5 text-xs text-[#6B7280]">{c.d}</p></div></div>))}</div></div>
    <div className="bg-[#FFF8F0] py-12"><div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-heading text-2xl font-bold text-[#2D2D2D]">Why This Guide?</h2><div className="mt-8 grid gap-6 sm:grid-cols-3">{[{ i: "🧩", t: "Budget-Friendly", d: "Every activity uses common household items — no expensive toys or equipment required" }, { i: "🧠", t: "Science-Backed", d: "Based on canine and feline cognitive science — activities designed to engage natural instincts" }, { i: "📱", t: "Always With You", d: "PDF on all devices — pull up new game ideas whenever your pet needs stimulation" }].map((b) => (<div key={b.t}><span className="text-3xl">{b.i}</span><h3 className="font-heading mt-2 font-semibold text-[#2D2D2D]">{b.t}</h3><p className="mt-1 text-sm text-[#6B7280]">{b.d}</p></div>))}</div></div></div>
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8"><h2 className="font-heading text-center text-2xl font-bold text-[#2D2D2D]">What Pet Parents Say</h2><div className="mt-6 space-y-4">{T.map((t) => (<div key={t.n} className="rounded-xl border border-[#E9EDDE] bg-white p-5"><div className="flex items-center gap-2"><span className="font-heading text-sm font-semibold text-[#2D2D2D]">{t.n}</span><span className="text-[#F4A261] text-sm">{"★".repeat(t.r)}</span></div><p className="mt-2 text-sm text-[#4A4A4A] leading-relaxed">{t.t}</p></div>))}</div></div>
    <div className="border-t border-[#E9EDDE] bg-gradient-to-b from-[#FFF8F0] to-white py-12"><div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-heading text-2xl font-bold text-[#2D2D2D]">Turn Your Home into a Pet Playground</h2><div className="mt-6"><span className="font-heading text-4xl font-bold text-[#FF7F5C]">$12.99</span><p className="mt-1 text-sm text-[#6B7280]">Instant PDF download · 30-day money-back guarantee</p><a href={P} className="btn-primary mt-4 inline-block text-base px-10 py-4">Buy Now — Instant Download</a></div><div className="mt-10 rounded-2xl border-2 border-[#F4A261] bg-white p-6 shadow-md"><span className="inline-flex items-center rounded-full bg-[#F4A261] px-3 py-1 text-xs font-bold text-white">BEST VALUE</span><h3 className="font-heading mt-3 text-lg font-semibold text-[#2D2D2D]">Get the Complete Pet Library</h3><p className="mt-1 text-sm text-[#6B7280]">Includes this guide plus all our premium eBooks — enrichment, training, health, travel, and more.</p><div className="mt-3 flex items-center justify-center gap-2"><span className="text-lg text-[#6B7280] line-through">Over $120</span><span className="font-heading text-2xl font-bold text-[#FF7F5C]">$49.99</span></div><a href={B} className="btn-secondary mt-3 inline-block">Get the Bundle Instead</a></div></div></div>
  </div>);
}
