import { createFileRoute } from "@tanstack/react-router";
const S = "https://pawandfound.store";
const B = "https://buy.stripe.com/8x28wPg2i9SE6MN7ao2cg0K";
const P = "https://buy.stripe.com/7sYeVd03kfcY2wx7ao2cg15";
const T = [{ n: "Mia R.", t: "Our rescue was terrified of everything when we brought her home. The 3-3-3 rule in this book gave us a realistic timeline instead of expecting overnight miracles. Six months later she's a different dog — confident, playful, and so loved.", r: 5 }, { n: "Daniel K.", t: "I've fostered dozens of dogs and this is the guide I now give every adopter. The trust-building exercises are gentle and effective. It covers trauma responses without being clinical or scary.", r: 5 }, { n: "Angela P.", t: "We almost gave up after the first month because our rescue was so shut down. This book helped us understand that what looked like rejection was actually fear. We followed the decompression protocol and now he's the heart of our family.", r: 5 }];

export const Route = createFileRoute("/ebooks/rescue-dog-rehab")({
  component: Page,
  head: () => ({ meta: [{ title: "Rescue Dog Rehabilitation Guide — Paw & Found" }, { name: "description", content: "Help your rescue dog heal, trust, and thrive. Covers decompression, trust-building, routines, socialization, and common challenges." }], links: [{ rel: "canonical", href: `${S}/ebooks/rescue-dog-rehab` }] }),
});

function Page() {
  const chapters = [
    { c: "1", t: "Understanding Your Rescue Dog's Past", d: "How trauma, neglect, and shelter life shape behavior — and why patience is your most powerful tool" },
    { c: "2", t: "The 3-3-3 Rule: Decompression Timeline", d: "What to expect in the first 3 days, 3 weeks, and 3 months — realistic milestones for settling in" },
    { c: "3", t: "Building Trust & Confidence", d: "Gentle exercises and daily rituals that help your dog feel safe, seen, and secure with you" },
    { c: "4", t: "Establishing Routines & Boundaries", d: "Why structure is comforting, not restrictive — creating predictable days that reduce anxiety" },
    { c: "5", t: "Socialization at Their Pace", d: "Slow, positive introductions to people, other dogs, and new environments without overwhelming them" },
    { c: "6", t: "Common Behavioral Challenges", d: "Resource guarding, separation anxiety, leash reactivity — understanding root causes and gentle solutions" },
    { c: "7", t: "When to Seek Professional Help", d: "Signs that you need a trainer or behaviorist — and how to find one who understands rescue dogs" },
  ];
  return (<div>
    <div className="bg-gradient-to-b from-[#FFF8F0] to-white"><div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8"><div className="flex flex-col items-center gap-8 md:flex-row md:items-start"><div className="flex-shrink-0"><img src="/images/ebook-rescue-dog-rehab.jpg" alt="Rescue Dog Rehabilitation Guide cover" className="w-56 rounded-xl shadow-2xl shadow-[#FF7F5C]/20 md:w-64" /></div><div className="flex-1 text-center md:text-left"><span className="inline-flex items-center rounded-full bg-[#FF7F5C]/15 px-3 py-1 text-sm font-semibold text-[#FF7F5C]">Premium eBook</span><h1 className="font-heading mt-3 text-3xl font-bold text-[#2D2D2D] sm:text-4xl">Rescue Dog Rehabilitation Guide</h1><p className="mt-4 text-lg text-[#6B7280] leading-relaxed max-w-xl">Give your rescue dog the patient, loving guidance they need to heal from their past and thrive in their forever home.</p><div className="mt-6 flex flex-wrap items-center gap-4 justify-center md:justify-start"><span className="font-heading text-3xl font-bold text-[#FF7F5C]">$14.99</span><a href={P} className="btn-primary text-base px-8 py-3">Buy Now — Instant Download</a></div><p className="mt-2 text-xs text-[#6B7280]">Secure payment via Stripe. 30-day money-back guarantee.</p></div></div></div></div>
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8"><h2 className="font-heading text-center text-2xl font-bold text-[#2D2D2D]">What's Inside</h2><p className="mt-2 text-center text-[#6B7280]">7 chapters of compassionate, practical guidance for rescue dog parents</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{chapters.map((ch) => (<div key={ch.c} className="flex gap-3 rounded-lg border border-[#E9EDDE] bg-white p-4"><span className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-[#FF7F5C]/15 text-sm font-bold text-[#FF7F5C]">{ch.c}</span><div><h3 className="font-heading text-sm font-semibold text-[#2D2D2D]">{ch.t}</h3><p className="mt-0.5 text-xs text-[#6B7280]">{ch.d}</p></div></div>))}</div></div>
    <div className="bg-[#FFF8F0] py-12"><div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-heading text-2xl font-bold text-[#2D2D2D]">Why This Guide?</h2><div className="mt-8 grid gap-6 sm:grid-cols-3">{[{ i: "🏠", t: "Realistic & Compassionate", d: "No quick fixes — honest timelines and gentle methods that respect your dog's unique history" }, { i: "🩺", t: "Behaviorist-Reviewed", d: "Every protocol reviewed by certified animal behaviorists specializing in trauma and rehabilitation" }, { i: "📱", t: "Always With You", d: "PDF on all devices — reference during vet visits, training sessions, or quiet moments of progress" }].map((b) => (<div key={b.t}><span className="text-3xl">{b.i}</span><h3 className="font-heading mt-2 font-semibold text-[#2D2D2D]">{b.t}</h3><p className="mt-1 text-sm text-[#6B7280]">{b.d}</p></div>))}</div></div></div>
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8"><h2 className="font-heading text-center text-2xl font-bold text-[#2D2D2D]">What Rescue Parents Say</h2><div className="mt-6 space-y-4">{T.map((t) => (<div key={t.n} className="rounded-xl border border-[#E9EDDE] bg-white p-5"><div className="flex items-center gap-2"><span className="font-heading text-sm font-semibold text-[#2D2D2D]">{t.n}</span><span className="text-[#F4A261] text-sm">{"★".repeat(t.r)}</span></div><p className="mt-2 text-sm text-[#4A4A4A] leading-relaxed">{t.t}</p></div>))}</div></div>
    <div className="border-t border-[#E9EDDE] bg-gradient-to-b from-[#FFF8F0] to-white py-12"><div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 text-center"><h2 className="font-heading text-2xl font-bold text-[#2D2D2D]">Ready to Help Your Rescue Thrive?</h2><div className="mt-6"><span className="font-heading text-4xl font-bold text-[#FF7F5C]">$14.99</span><p className="mt-1 text-sm text-[#6B7280]">Instant PDF download · 30-day money-back guarantee</p><a href={P} className="btn-primary mt-4 inline-block text-base px-10 py-4">Buy Now — Instant Download</a></div><div className="mt-10 rounded-2xl border-2 border-[#F4A261] bg-white p-6 shadow-md"><span className="inline-flex items-center rounded-full bg-[#F4A261] px-3 py-1 text-xs font-bold text-white">BEST VALUE</span><h3 className="font-heading mt-3 text-lg font-semibold text-[#2D2D2D]">Get the Complete Pet Library</h3><p className="mt-1 text-sm text-[#6B7280]">Includes this guide plus all our premium eBooks — rescue, training, health, nutrition, and more.</p><div className="mt-3 flex items-center justify-center gap-2"><span className="text-lg text-[#6B7280] line-through">Over $120</span><span className="font-heading text-2xl font-bold text-[#FF7F5C]">$49.99</span></div><a href={B} className="btn-secondary mt-3 inline-block">Get the Bundle Instead</a></div></div></div>
  </div>);
}
